# Generated by Django 5.1.2 on 2024-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nasterii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gen',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Feminin'), ('nu doresc sa raspund', 'Nu doresc sa raspund')], max_length=30, null=True),
        ),
    ]
