# Generated by Django 5.1.2 on 2024-12-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_3', '0006_customuser_blocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='masina',
            name='stoc',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
