# Generated by Django 5.1.2 on 2025-01-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_3', '0007_masina_stoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produse', models.JSONField()),
                ('total_pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cantitate', models.IntegerField()),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
